# Robot arm controller
robot_arm_controller:
  type: "position_controllers/JointTrajectoryController"
  joints: [base_to_arm1, arm_2_to_arm_1]

# End effector controller
hand_ee_controller:
  type: "position_controllers/JointTrajectoryController"
  joints: [hand_to_arm2]

# Joint State Controller:
joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50
